# 网站基本配置
baseURL = 'https://example.org/'  # 替换为你的实际域名
languageCode = 'zh-cn'            # 设置为中文
title = '我的个人博客'               # 博客标题
theme = 'PaperMod'                # 使用PaperMod主题

# 网站参数配置
[params]
  # 作者信息
  author = "博主姓名"
  # 网站描述
  description = "一个记录生活和技术的个人博客"
  # 显示阅读时间
  ShowReadingTime = true
  # 显示分享按钮
  ShowShareButtons = true
  # 显示文章导航
  ShowPostNavLinks = true
  # 显示面包屑导航
  ShowBreadCrumbs = true
  # 显示代码复制按钮
  ShowCodeCopyButtons = true
  # 显示目录
  ShowToc = true
  # 目录默认展开
  TocOpen = false

  # 社交链接（可选）
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourusername"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:youremail@example.com"

# 菜单配置
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 30

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 40

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 50

# 标记语言配置
[markup]
  [markup.highlight]
    # 代码高亮主题
    style = "github"
    # 显示行号
    lineNos = true
